name: videocap
base: core20
version: '0.1'
summary: Capture and detect movements on video feeds
description: |
  This is my take of a simple video monitoring solution. The scope of the
  project is quite narrow for my specific use case. Detect movements,
  screenshot and send these images and videos offsite.

grade: stable
confinement: strict

# TODO: Add arm64 when https://snapcraft.io/ffmpeg as released an arm64 package to stable
architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]

layout:
  /var/videocap:
    type: tmpfs

apps:
  analyzer:
    command: bin/analyzer
    environment:
      ANALYZER: enabled
      VIDEOCAP_DATA: /var/videocap

  analyzer-service:
    command: bin/analyzer.sh
    daemon: simple
    environment:
      VIDEOCAP_DATA: /var/videocap
    plugs:
      - network

  ingest:
    command: bin/ingest.sh
    environment:
      VIDEOCAP_DATA: /var/videocap

  push-nextcloud:
    command: bin/push-nextcloud.sh
    plugs:
      - network

  recorder:
    command: bin/recorder.sh
    environment:
      RECORDER: enabled
    plugs:
      - network

  recorder-service:
    command: bin/recorder.sh
    daemon: simple
    plugs:
      - network

parts:
  analyzer:
    plugin: python
    source: analyzer
    stage-packages:
      - libice6
      - libsm6

  ingest:
    plugin: dump
    source: ingest

  nextcloud:
    plugin: dump
    source: nextcloud
    stage-packages:
      - curl

  services:
    plugin: dump
    source: services
    stage-packages:
      - inotify-tools
      - libtinfo5
    stage-snaps:
      - ffmpeg
