name: videocap
base: core20
version: '0.2'
summary: Capture and detect movements on video feeds
description: |
  This is my take of a simple video monitoring solution. The scope of the
  project is quite narrow for my specific use case. Detect movements,
  screenshot and send these images and videos offsite.

grade: stable
confinement: strict

# TODO: Add arm64 when https://snapcraft.io/ffmpeg as released an arm64 package to stable
architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]

layout:
  /var/videocap:
    type: tmpfs

apps:
  videocap-service:
    command: bin/videocap.sh
    daemon: simple
    environment:
      VIDEOCAP_DATA: /var/videocap
    plugs:
      - network

  nextcloud-service:
    command: bin/nextcloud.sh
    daemon: simple
    plugs:
      - network

parts:
  videocap:
    plugin: python
    source: videocap
    stage-packages:
      - libice6
      - libsm6

  nextcloud:
    plugin: dump
    source: nextcloud
    stage-packages:
      - curl

  services:
    plugin: dump
    source: services
    stage-packages:
      - inotify-tools
      - libtinfo5
    stage-snaps:
      - ffmpeg
